### ISSUE TITLE
This driver does not support retrieving URLs

### ISSUE THREAD

**Issue by reneroth** [fortrabbit/laravel-object-storage#10]
Trying to do `Storage::url($path)` on an `object-storage` disk will throw the error `This driver does not support retrieving URLs.`.

Solution seems to be easy enough, something like this should suffice (untested):

```php
    public function getUrl(string $path)
    {
        return 'https://' . env('OBJECT_STORAGE_HOST') . '/' . $path;
    }
```

**Comment by reneroth** [comment]
If you have a preference on how this should be done, I'll put in a PR.

**Comment by ostark** [comment]
Sorry, I missed this. If it's still needed, please give it a try:
https://github.com/fortrabbit/laravel-object-storage/pull/13

**Comment by reneroth** [comment]
Thank you! ❤️

**Comment by ostark** [comment]
Better late than never.
