### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by reneroth** [fortrabbit/laravel-object-storage#11]
Dependency conflict for illuminate/filesystem and illuminate/support between fortrabbit/laravel-object-storage and laravel/framework, but from what I could see there have been no breaking changes, so only the composer.json would need to be updated to allow both ^9.0 and ^10.0 for those illuminate packages.

**Comment by ostark** [comment]
finally 
https://github.com/fortrabbit/laravel-object-storage/commit/fc60f115a5be48b8eba18a385f435c0491b865f6
